/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "clavesRPC.h"
#include "claves.h"


bool_t
set_value_1_svc(set_value_args arg1, int *result,  struct svc_req *rqstp)
{
	struct Paquete p;
    p.x = arg1.value3.x_rpc;
    p.y = arg1.value3.y_rpc;
    p.z = arg1.value3.z_rpc;

    *result = set_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2.V_value2_val, p);
    return TRUE;
}


bool_t
get_value_1_svc(char *key, get_value_res *result, struct svc_req *rqstp)
{
    char value1[256];
    int N_value2;
    float V_value2[32];
    struct Paquete p;
	result->value1 = NULL;
    result->V_value2.V_value2_len = 0;
    result->V_value2.V_value2_val = NULL;
    result->N_value2 = 0;
    result->codigo_error = 0;
    result->codigo_error = get_value(key, value1, &N_value2, V_value2, &p);

    if (result->codigo_error == -1){
		result->value1 = malloc(1);
    	result->value1[0] = '\0';
    	result->V_value2.V_value2_len = 0;
    	result->V_value2.V_value2_val = NULL;
	
        return TRUE;  
	}
    result->value1 = malloc(strlen(value1) + 1);
	strcpy(result->value1, value1);
    result->N_value2      = N_value2;

    result->V_value2.V_value2_len = N_value2;
    result->V_value2.V_value2_val = malloc(N_value2 * sizeof(float));
    memcpy(result->V_value2.V_value2_val, V_value2, N_value2 * sizeof(float));

    result->value3.x_rpc = p.x;
    result->value3.y_rpc = p.y;
    result->value3.z_rpc = p.z;
    return TRUE;
}


bool_t
modify_value_1_svc(set_value_args arg1, int *result,  struct svc_req *rqstp)
{
	struct Paquete p;
	p.x = arg1.value3.x_rpc;
    p.y = arg1.value3.y_rpc;
    p.z = arg1.value3.z_rpc;

    *result = modify_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2.V_value2_val, p);
    return TRUE;
}


bool_t
delete_key_1_svc(char *key, int *result,  struct svc_req *rqstp)
{
	*result = delete_key(key);
	printf("La tupla con key %s, ha sido borrada.\n", key);
	return TRUE;
}

bool_t
exist_1_svc(char *key, int *result,  struct svc_req *rqstp)
{
	*result = exist(key);
	printf("La tupla con key %s, existe.\n", key);
	return TRUE;
}

bool_t
destroy_1_svc(int *result, struct svc_req *rqstp)
{
	*result = destroy();
	return TRUE;
}

int
claves_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);
	return 1;
}