/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "clavesRPC.h"
#include "claves.h"


bool_t
set_value_1_svc(set_value_args arg1, int *result,  struct svc_req *rqstp)
{
	struct Paquete p;
    p.x = arg1.value3.x_rpc;
    p.y = arg1.value3.y_rpc;
    p.z = arg1.value3.z_rpc;

    *result = set_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2.V_value2_val, p);
    return TRUE;
}


bool_t
get_value_1_svc(char *key, get_value_res *result, struct svc_req *rqstp)
{

    return TRUE;
}


bool_t
modify_value_1_svc(set_value_args arg1, int *result,  struct svc_req *rqstp)
{
	struct Paquete p;
	p.x = arg1.value3.x_rpc;
    p.y = arg1.value3.y_rpc;
    p.z = arg1.value3.z_rpc;

    *result = modify_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2.V_value2_val, p);
    return TRUE;
}


bool_t
delete_key_1_svc(char *key, int *result,  struct svc_req *rqstp)
{
	*result = delete_key(key);
	printf("La tupla con key %s, ha sido borrada.\n", key);
	return TRUE;
}

bool_t
exist_1_svc(char *key, int *result,  struct svc_req *rqstp)
{
	*result = exist(key);
	printf("La tupla con key %s, existe.\n", key);
	return TRUE;
}

bool_t
destroy_1_svc(int *result, struct svc_req *rqstp)
{
	*result = destroy();
	return TRUE;
}

int
claves_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);
	return 1;
}